### ISSUE TITLE
Nest accessory failing to connect

### ISSUE THREAD

**Issue by legotheboss** [michaelrcarroll/HAP-Accessories#6]
Been running into this error with the Nest Accessory...

Any fixes?

````
Parsing accessory factory: NestThermostat_accfactory.js
Asking Nest for Thermostats...
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at getNestThermostats (/home/pi/HAP-NodeJS/accessories/NestThermostat_accfactory.js:104:20)
    at /home/pi/HAP-NodeJS/accessories/NestThermostat_accfactory.js:393:3
    at Object.<anonymous> (/home/pi/HAP-NodeJS/accessories/NestThermostat_accfactory.js:401:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
````

**Comment by legotheboss** [comment]
Fixed the issue by getting a new authentication code from the link

**Comment by svicino** [comment]
I am having this issue now, and a new authentication code is not resolving the issue.

**Comment by michaelrcarroll** [comment]
I'd recommend migrating to https://github.com/KraigM/homebridge-nest. My new apartment no longer has AC, so I don't use the Nest anymore nor do I maintain this setup.

The homebridge community is much larger and you're more likely to find proper support there.
